### ISSUE TITLE
link do spark/jfortin/shinyMethyl does not work

### ISSUE THREAD

**Issue by MarcinKosinski** [Jfortin1/shinyMethyl#1]
@Jfortin1 I am going through your vignette and it appeared that the link http://spark.rstudio.com/jfortin/shinyMethyl/ provided in the `Introduction` does not work.

404 pag not found

**Comment by Jfortin1** [comment]
thanks working on it now :)

**Comment by Niladri-B** [comment]
@Jfortin1 Hi! I think I am facing a similar problem. Only now I get the following error message: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8F59B8A3AE38B889</RequestId>
<HostId>
7l5e+1pjnB5MBokQ+peE3La75CuxKfl9Nhhx8Rp/YRFcUSyO6wUEqRGiV29k9qsRJq8R4Dft0fA=
</HostId>
</Error>
