### ISSUE TITLE
Error in object@greenControls[[i]][, o] : incorrect number of dimensions

### ISSUE THREAD

**Issue by wvictor14** [Jfortin1/shinyMethyl#2]
Dear @Jfortin1,

I would like to try using ShinyMethyl for my preprocessing and analysis of combined 450k+EPIC data from 4 different independent sources. 

I'm encountering an error when I run the 'runShinyMethyl()' function on my shinyMethylSet. I think it might have something to with how I used 'combineArrays' from the Minfi package to combine the 4 rgsets, but I'm not sure how to troubleshoot because I'm unfamiliar with these object types.

I have one dataset ran on an EPIC array, and 3x450k datasets that I have all combined into one rgset using 'combineArrays' from Minfi. This function also converts the EPIC dataset to a 'virtual' 450k (by dropping non-overlapping probes). 

Here is what happens:

`rgset`
> RGChannelSet (storageMode: lockedEnvironment)
> assayData: 575719 features, 32 samples 
>   element names: Green, Red 
> An object of class 'AnnotatedDataFrame'
>   sampleNames: 200925700116_R04C01 200925700116_R03C01 ... 9974366131_R06C02 (32 total)
>   varLabels: Sample_Name Sample_Well ... Age (20 total)
>   varMetadata: labelDescription
> Annotation
>   array: IlluminaHumanMethylation450k
>   annotation: ilmn12.hg19

`myShinyMethylSet <- shinySummarize(rgset)`

> [shinySummarize] Extracting Red and Green channels 
> [shinySummarize] Raw preprocessing 
> [shinySummarize] Mapping to genome 
> [shinySummarize] Computing quantiles 
> [shinySummarize] Computing principal components 

`myShinyMethylSet`

>  Object:  shinyMethylSet 
>  Number of samples:  32 
>  Phenotype:  20 covariates 
>  Origin object:  RGChannelSet 
>  Array:  IlluminaHumanMethylation450k 

`runShinyMethyl(myShinyMethylSet)`
> Error in object@greenControls[[i]][, o] : incorrect number of dimensions

Any help would be appreciated,
Thanks,
Victor

**Comment by Jfortin1** [comment]
Thanks for bringing this to my attention. The issue is now solved; the changes are incorporated on this github repo, and should be pushed to Bioconductor soon. Thanks
