### ISSUE TITLE
Problems Installing/Running shinyMethyl Using Guide

### ISSUE THREAD

**Issue by Graeme-Smith** [Jfortin1/shinyMethyl#4]
Hi,
The instructions for installation of the shinyMethylData package at https://github.com/Jfortin1/shinyMethyl have a couple of issues:

>install_github("shinyMethylData", "jfortin1")

Returns the error message:

Username parameter is deprecated. Please use jfortin1/shinyMethylData 

As suggested this works:
> install_github("jfortin1/shinyMethylData")

And rather than running ShinyMethyl with these arguments:
>runShinyMethyl(tcga.summary.raw, tcga.summary.norm)
Error in runShinyMethyl(tcga.summary.raw, tcga.summary.norm) : 
  object 'tcga.summary.raw' not found

This is required with summary and tcga swapped around:

runShinyMethyl(summary.tcga.raw, summary.tcga.norm)

Regards

**Comment by Jfortin1** [comment]
Thanks so much for pointing that out!
