### ISSUE TITLE
Package fails on Bioconductor devel version (3.17)

### ISSUE THREAD

**Issue by jorainer** [Jfortin1/shinyMethyl#6]
Dear package developers (@Jfortin1 @kasperdanielhansen),

your package `shinyMethyl` is currently failing on the Bioconductor [devel branch (3.17)](http://bioconductor.org/checkResults/3.17/bioc-LATEST/shinyMethyl/). Could you please have a look into this and fix? Also, please update the maintainer email address in the package DESCRIPTION because it is no longer valid.

Thanks!
jo

**Comment by Jfortin1** [comment]
@jorainer Thanks Jo -- wow, the package deserves some code refactoring. Getting to it now

**Comment by Jfortin1** [comment]
Changed my email now to my perm gmail address. I've sent an email to packages@bioconductor.org so that I can push to Bioc, but let me know if I should ask someone else directly

**Comment by jorainer** [comment]
What people usually do is to post to the [BioC mailing list](https://stat.ethz.ch/mailman/listinfo/bioc-devel) - you should get a reply there usually very soon.

**Comment by Jfortin1** [comment]
Fixed in v1.35.7.
